import type { PrerequisiteSuggestion, SkillDefinition } from '../learning/contracts';

const maths = 'https://www.gov.uk/government/publications/national-curriculum-in-england-mathematics-programmes-of-study/national-curriculum-in-england-mathematics-programmes-of-study';
const english = 'https://www.gov.uk/government/publications/national-curriculum-in-england-english-programmes-of-study/national-curriculum-in-england-english-programmes-of-study';

/** Declared scope, not task availability. Selectors derive bands from approved
 * delivered TaskDefinitions; a registry row alone never delivers a task. */
export const SKILLS = [
  { skillId: 'M01', label: 'Missing totals', objectiveId: 'M01-addition-subtraction', focus: 'Addition/subtraction and missing totals', availability: 'M1', declaredBands: ['support', 'core', 'stretch'], curriculum: [{ sourceUrl: maths, section: 'Number — addition and subtraction', programmeBand: 'Years 3 and 4' }], demandRationale: 'Whole-number reasoning; starter bridge is introductory support, not a proficiency test.' },
  { skillId: 'M02', label: 'Equal groups', objectiveId: 'M02-multiplication-groups', focus: 'Multiplication facts and equal groups', availability: 'M2', declaredBands: ['support', 'core', 'stretch'], curriculum: [{ sourceUrl: maths, section: 'Number — multiplication and division', programmeBand: 'Years 3 and 4' }], demandRationale: 'Facts and represented equal groups, including bounded patterns.' },
  { skillId: 'M03', label: 'Division facts', objectiveId: 'M03-exact-division', focus: 'Exact division and inverse facts', availability: 'M2', declaredBands: ['support', 'core', 'stretch'], curriculum: [{ sourceUrl: maths, section: 'Number — multiplication and division', programmeBand: 'Years 3 and 4' }], demandRationale: 'Exact quotients linked to known multiplication facts.' },
  { skillId: 'M04', label: 'Two constraints', objectiveId: 'M04-integer-scaling', focus: 'Integer scaling and two constraints', availability: 'M1', declaredBands: ['support', 'core', 'stretch'], curriculum: [{ sourceUrl: maths, section: 'Number — multiplication and division: integer scaling and correspondence problems', programmeBand: 'Years 3 and 4' }], demandRationale: 'Merchant checks total and multiplicative relationship; no formal ratio algebra or contextual reading assessment.' },
  { skillId: 'M05', label: 'Fractions', objectiveId: 'M05-equivalence-quantity', focus: 'Equivalent fractions and fractions of quantities', availability: 'M2', declaredBands: ['support', 'core', 'stretch'], curriculum: [{ sourceUrl: maths, section: 'Number — fractions', programmeBand: 'Years 3 and 4' }, { sourceUrl: maths, section: 'Number — fractions (including decimals and percentages)', programmeBand: 'Year 5 (selected stretch)' }], demandRationale: 'Keep the unit whole fixed; selected Year 5 equivalence extends Year 4 planning.' },
  { skillId: 'M06', label: 'Decimals', objectiveId: 'M06-decimal-place-value', focus: 'Decimal place value and comparison', availability: 'M2', declaredBands: ['support', 'core', 'stretch'], curriculum: [{ sourceUrl: maths, section: 'Number — fractions (including decimals)', programmeBand: 'Year 4' }, { sourceUrl: maths, section: 'Number — fractions (including decimals and percentages)', programmeBand: 'Year 5 (selected stretch)' }], demandRationale: 'Tenths/hundredths and selected thousandths, represented exactly by scaled integers.' },
  { skillId: 'M07', label: 'Money and measures', objectiveId: 'M07-money-metric', focus: 'Money, change and metric quantities', availability: 'M2', declaredBands: ['support', 'core', 'stretch'], curriculum: [{ sourceUrl: maths, section: 'Measurement: money and measures', programmeBand: 'Years 3 and 4' }], demandRationale: 'Exact pence/metric quantities and multistep change; bridge metres remain context for M01.' },
  { skillId: 'M08', label: 'Time', objectiveId: 'M08-clock-duration', focus: 'Clocks, durations and simple timetables', availability: 'M2', declaredBands: ['support', 'core', 'stretch'], curriculum: [{ sourceUrl: maths, section: 'Measurement: time', programmeBand: 'Years 3 and 4' }, { sourceUrl: maths, section: 'Statistics: tables, including timetables', programmeBand: 'Year 5 (selected stretch)' }], demandRationale: 'Whole-minute clock/duration reasoning and selected simple timetable demands.' },
  { skillId: 'M09', label: 'Shapes and turns', objectiveId: 'M09-shape-symmetry-turn', focus: 'Shape properties, symmetry and turns', availability: 'M2', declaredBands: ['support', 'core', 'stretch'], curriculum: [{ sourceUrl: maths, section: 'Geometry — properties of shapes; position and direction', programmeBand: 'Years 3 and 4' }], demandRationale: 'Use supplied shape evidence and bounded turns; decorative coordinates are not measured lengths.' },
  { skillId: 'M10', label: 'Data', objectiveId: 'M10-tables-charts', focus: 'Tables, charts and comparison', availability: 'M2', declaredBands: ['support', 'core', 'stretch'], curriculum: [{ sourceUrl: maths, section: 'Statistics', programmeBand: 'Years 3 and 4' }, { sourceUrl: maths, section: 'Statistics: line graphs', programmeBand: 'Year 5 (selected stretch)' }], demandRationale: 'Read supplied data, compare and solve bounded multistep questions; selected line graph stretch.' },
  { skillId: 'E01', label: 'Spelling patterns', objectiveId: 'E01-spelling-affixes', focus: 'Spelling patterns and affixes', availability: 'M2', declaredBands: ['support', 'core', 'stretch'], curriculum: [{ sourceUrl: english, section: 'Word reading; writing — transcription; English Appendix 1: spelling', programmeBand: 'Years 3–4' }], demandRationale: 'Finite reviewed word/affix choices; English uses the official two-year band.' },
  { skillId: 'E02', label: 'Homophones', objectiveId: 'E02-homophones', focus: 'Homophones in context', availability: 'M2', declaredBands: ['support', 'core', 'stretch'], curriculum: [{ sourceUrl: english, section: 'Writing — transcription; English Appendix 1: spelling', programmeBand: 'Years 3–4' }], demandRationale: 'Choose the reviewed homophone for its supplied context.' },
  { skillId: 'E03', label: 'Word meanings', objectiveId: 'E03-contextual-vocabulary', focus: 'Contextual meaning, synonyms and opposites', availability: 'M2', declaredBands: ['support', 'core', 'stretch'], curriculum: [{ sourceUrl: english, section: 'Reading — comprehension: vocabulary and meaning in context', programmeBand: 'Years 3–4' }], demandRationale: 'Context supplies evidence for finite vocabulary choices; avoid ambiguous alternatives.' },
  { skillId: 'E04', label: 'Word classes', objectiveId: 'E04-word-classes', focus: 'Word classes in supplied sentences', availability: 'M2', declaredBands: ['support', 'core', 'stretch'], curriculum: [{ sourceUrl: english, section: 'Writing — vocabulary, grammar and punctuation; English Appendix 2: earlier terminology consolidated', programmeBand: 'Years 3–4 (earlier consolidation)' }], demandRationale: 'Consolidate earlier word-class terminology in Year 3–4 sentences, not an invented Year 4 statutory list.' },
  { skillId: 'E05', label: 'Clauses', objectiveId: 'E05-clauses-conjunctions', focus: 'Clauses and conjunctions', availability: 'M2', declaredBands: ['support', 'core', 'stretch'], curriculum: [{ sourceUrl: english, section: 'Writing — composition; vocabulary, grammar and punctuation', programmeBand: 'Years 3–4' }], demandRationale: 'Bounded clause/conjunction choices preserve supplied meaning.' },
  { skillId: 'E06', label: 'Punctuation', objectiveId: 'E06-punctuation', focus: 'End punctuation, commas and apostrophes', availability: 'M1', declaredBands: ['support', 'core', 'stretch'], curriculum: [{ sourceUrl: english, section: 'Writing — vocabulary, grammar and punctuation; English Appendix 2', programmeBand: 'Years 3–4 (earlier end-punctuation consolidation)' }], demandRationale: 'Starter endings consolidate earlier learning; later comma/apostrophe tasks need individual reviewed contexts.' },
  { skillId: 'E07', label: 'Direct speech', objectiveId: 'E07-direct-speech', focus: 'Direct-speech punctuation', availability: 'M2', declaredBands: ['support', 'core', 'stretch'], curriculum: [{ sourceUrl: english, section: 'Writing — vocabulary, grammar and punctuation; English Appendix 2: direct speech', programmeBand: 'Years 3–4' }], demandRationale: 'Finite speech edits cover inverted commas and other required punctuation.' },
  { skillId: 'E08', label: 'Retrieve details', objectiveId: 'E08-retrieval-instructions', focus: 'Detail retrieval and written instructions', availability: 'M2', declaredBands: ['support', 'core', 'stretch'], curriculum: [{ sourceUrl: english, section: 'Reading — comprehension', programmeBand: 'Years 3–4' }], demandRationale: 'Retrieve explicit details from assessed text; listening support qualifies reading evidence.' },
  { skillId: 'E09', label: 'Inference and clues', objectiveId: 'E09-inference-prediction', focus: 'Inference/prediction with a supporting clue', availability: 'M2', declaredBands: ['support', 'core', 'stretch'], curriculum: [{ sourceUrl: english, section: 'Reading — comprehension: inference, justification and prediction', programmeBand: 'Years 3–4' }, { sourceUrl: english, section: 'Reading — comprehension', programmeBand: 'Years 5–6 (selected text demand)' }], demandRationale: 'A finite inference plus textual clue; selected higher text demand uses the official Years 5–6 band.' },
  { skillId: 'E10', label: 'Sequence and edit', objectiveId: 'E10-narrative-editing', focus: 'Narrative sequencing and short passage editing', availability: 'M2', declaredBands: ['support', 'core', 'stretch'], curriculum: [{ sourceUrl: english, section: 'Reading — comprehension; writing — composition: drafting, evaluating and editing', programmeBand: 'Years 3–4' }], demandRationale: 'Reviewed tile sequencing/editing is a bounded composition substitute, not extended free-writing assessment.' },
] as const satisfies readonly SkillDefinition[];

/** Educational suggestions only; never quest locks or diagnoses. */
export const PREREQUISITE_SUGGESTIONS = [
  { prerequisiteSkillId: 'M02', skillId: 'M03', rationale: 'Multiplication supports inverse division facts.' },
  { prerequisiteSkillId: 'M02', skillId: 'M04', rationale: 'Equal groups support integer scaling.' },
  { prerequisiteSkillId: 'M03', skillId: 'M05', rationale: 'Exact division supports fractions of quantities, not every fraction task.' },
  { prerequisiteSkillId: 'M06', skillId: 'M07', rationale: 'Decimal place value supports decimal money contexts, not every measure task.' },
  { prerequisiteSkillId: 'E04', skillId: 'E05', rationale: 'Word classes support clause construction.' },
  { prerequisiteSkillId: 'E06', skillId: 'E07', rationale: 'End punctuation supports direct-speech punctuation.' },
  { prerequisiteSkillId: 'E08', skillId: 'E09', rationale: 'Retrieve textual evidence before an inference with a clue.' },
  { prerequisiteSkillId: 'E08', skillId: 'E10', rationale: 'Retrieve passage details to support sequencing/editing.' },
] as const satisfies readonly PrerequisiteSuggestion[];
