import type { TaskDefinition, TaskFamilyManifest } from '../learning/contracts';
import { canonicalQuestionId } from '../learning/identity';

const curriculum = {
  sourceUrl: 'https://www.gov.uk/government/publications/national-curriculum-in-england-english-programmes-of-study/national-curriculum-in-england-english-programmes-of-study',
  section: 'Year 1 — Writing: vocabulary, grammar and punctuation: beginning to punctuate sentences using a capital letter and a full stop, question mark or exclamation mark; English Appendix 2, Year 1 — Punctuation',
  programmeBand: 'Year 1 end-punctuation consolidated in Years 3–4',
};
const neutralText = 'Read the scene and each line. Choose an ending for every space. You can change your choices. When every space is filled, choose Check.';
const options = [{ id: '.', label: '.' }, { id: '?', label: '?' }, { id: '!', label: '!' }] as const;
type AuthoredTask = Readonly<{
  key: string; context: string; lines: readonly (readonly [string, string])[];
  accepted: readonly Readonly<Record<string, string>>[];
  demand: string; explanation: string; hints: readonly [string, string]; worked: string;
}>;

// Explicit authored contexts/answers, never generated by swapping names or marks.
const authored: readonly AuthoredTask[] = [
  {
    key: 'spellbook-anchor',
    context: 'The reader asks where the missing books are. Then the reader spots them. The discovery may be calm or excited; the reader is no longer asking where they are.',
    lines: [['question', 'Where are my magic books'], ['discovery', 'Look, there they are']],
    accepted: [{ question: '?', discovery: '.' }, { question: '?', discovery: '!' }],
    demand: 'Introductory two-line search and discovery; distinguish a real information question from a finding with two legitimate tones. Both lines form one question for learning evidence.',
    explanation: 'The first line asks where the books are, so it ends with a question mark. The second tells of a discovery: a full stop is a calm observation and an exclamation mark is an excited one. Both discoveries work equally well. A question mark would make the discovery uncertain, outside this scene.',
    hints: ['Think about what changes between searching and finding.', 'Use the scene to decide what each line is doing. The two lines need not have the same ending.'],
    worked: 'Where are my magic books? Look, there they are. This is a question followed by a calm discovery. Where are my magic books? Look, there they are! This is the same question followed by an excited discovery. Both complete versions are correct.',
  },
  {
    key: 'spellbook-01',
    context: 'Write a calm, factual entry in a growing diary. The writer is recording what is visible, without asking or showing surprise.',
    lines: [['record', 'The seed has two leaves']], accepted: [{ record: '.' }],
    demand: 'Recognise a neutral factual record, with a specified calm writing purpose rather than a universally fixed ending for these words.',
    explanation: 'A full stop fits this calm diary record. A question mark would ask for confirmation, and an exclamation mark would add emphasis or excitement that this entry does not call for.',
    hints: ['Think about why the writer is making this diary entry.', 'Compare the job of a record with the job of a message asking someone to respond.'],
    worked: 'The seed has two leaves. The full stop finishes a calm factual record. The other endings would change the purpose or tone given in the scene.',
  },
  {
    key: 'spellbook-02',
    context: 'The lamp keeper cannot see the lantern. The keeper calmly asks a friend for a yes-or-no answer.',
    lines: [['lantern', 'Is the lantern lit']], accepted: [{ lantern: '?' }],
    demand: 'Identify a genuine yes-or-no information question, contrasting with the anchor’s where question.',
    explanation: 'Is the lantern lit? asks for an answer, so it needs a question mark here. A full stop does not signal the question; an exclamation mark would not match this calm request for information.',
    hints: ['Think about what the keeper needs from the friend.', 'Imagine what a useful reply from the friend would do.'],
    worked: 'Is the lantern lit? The keeper is asking for information. The question mark shows that a reply is wanted.',
  },
  {
    key: 'spellbook-03',
    context: 'A gardener politely asks whether a helper can carry a basket. This is a real, calm question: the helper may say yes or no.',
    lines: [['request', 'Could you carry this basket']], accepted: [{ request: '?' }],
    demand: 'Recognise a polite request framed as a genuine question, not a shouted command.',
    explanation: 'Could you carry this basket? is a polite question in this scene. A question mark fits the invitation to answer. A full stop or an exclamation mark would not express the supplied calm question.',
    hints: ['Notice how the gardener approaches the helper.', 'Consider whether the helper has been invited to respond before doing anything.'],
    worked: 'Could you carry this basket? This polite request is phrased as a question and allows a reply, so it ends with a question mark.',
  },
  {
    key: 'spellbook-04',
    context: 'A traveller writes a calm statement about a thought in a private journal. The traveller is describing being curious, not directly asking anyone for an answer.',
    lines: [['thought', 'I wonder where the path leads']], accepted: [{ thought: '.' }],
    demand: 'Distinguish an indirect wondering statement from a direct question; the word where alone does not determine the ending.',
    explanation: 'I wonder where the path leads. reports a thought in this journal. The full stop suits the calm statement. The word where occurs inside it but does not turn the whole sentence into a direct question here; excitement is not part of the scene.',
    hints: ['Look at the beginning of the whole line, not just one word inside it.', 'Use the journal context to decide whose thought is being described.'],
    worked: 'I wonder where the path leads. This sentence calmly reports the traveller’s wondering. A direct question would have different wording, such as Where does the path lead?',
  },
  {
    key: 'spellbook-05',
    context: 'A watcher admires the night sky. The words may express quiet admiration or an excited response. The watcher is not asking what the sky is.',
    lines: [['admiration', 'What a beautiful sky']], accepted: [{ admiration: '.' }, { admiration: '!' }],
    demand: 'Recognise admiration rather than a question despite initial What, allowing both a quiet and an emphatic reading.',
    explanation: 'What a beautiful sky. can express quiet admiration; What a beautiful sky! makes it emphatic. Both tones are offered here. A question mark would suggest a question, but the watcher is admiring the sky rather than requesting information.',
    hints: ['Consider the watcher’s purpose in speaking.', 'The first word is only one clue. Read the whole line with the scene in mind.'],
    worked: 'What a beautiful sky. is the quiet version. What a beautiful sky! is the excited version. Both match the admiration allowed in this scene; neither asks for information.',
  },
  {
    key: 'spellbook-06',
    context: 'A scout sees a branch falling towards a friend and shouts an urgent warning. Show the alarm in the ending, not a calm report or a question.',
    lines: [['warning', 'The branch is falling']], accepted: [{ warning: '!' }],
    demand: 'Use an emphatic ending for an explicitly urgent warning; recognise that statement-shaped words can carry alarm.',
    explanation: 'The branch is falling! uses an exclamation mark to show the urgent alarm requested here. A full stop could suit a calm report in another scene, and a question mark could ask for confirmation, but neither expresses this shouted warning.',
    hints: ['Think about how quickly the friend needs to notice this message.', 'Compare the feeling in an urgent warning with a calm description.'],
    worked: 'The branch is falling! The exclamation mark supplies the emphatic alarm the scene asks for. These words could have a different ending in a different scene.',
  },
  {
    key: 'spellbook-07',
    context: 'A guide writes one calm direction on a walking card. It is a routine instruction, without alarm, excitement or a request for confirmation.',
    lines: [['direction', 'Turn left at the oak']], accepted: [{ direction: '.' }],
    demand: 'Recognise that a calm direction can end with a full stop; imperative wording alone does not require emphasis.',
    explanation: 'Turn left at the oak. is a calm written direction. The full stop suits this routine instruction. An exclamation mark would add emphasis not requested here; a question mark would change the direction into a query.',
    hints: ['Think about how the walking card will be used.', 'Read the description of the guide’s tone as well as the words on the card.'],
    worked: 'Turn left at the oak. The full stop ends a routine direction. A command or instruction does not always need an exclamation mark.',
  },
  {
    key: 'spellbook-08',
    context: 'An explorer discovers an open hidden door, calmly or excitedly. Then the explorer calmly asks the group who has the key, expecting an answer.',
    lines: [['door', 'The hidden door is open'], ['key', 'Who has the key']],
    accepted: [{ door: '.', key: '?' }, { door: '!', key: '?' }],
    demand: 'Switch from a discovery to an information question in the reverse order from the anchor; preserve both allowed discovery tones.',
    explanation: 'The hidden door is open. is a calm discovery and The hidden door is open! is an excited one; both fit. Who has the key? is the separate information question. Questioning the discovery or failing to mark the request for information changes the supplied scene.',
    hints: ['Track what the explorer does first and what happens next.', 'Consider the job of each line separately before comparing your choices.'],
    worked: 'The hidden door is open. Who has the key? works, and The hidden door is open! Who has the key? works too. The discovery may have either tone; the second line still asks for information.',
  },
  {
    key: 'spellbook-09',
    context: 'A walker is unsure whether a friend brought the map. The walker uses these words as a calm question to check, expecting yes or no, not as a statement.',
    lines: [['confirmation', 'You brought the map']], accepted: [{ confirmation: '?' }],
    demand: 'Use the supplied communicative purpose to identify a confirmation question even with statement word order.',
    explanation: 'You brought the map? uses a question mark because the unsure walker is checking. Statement word order does not prevent a question in this dialogue. A full stop would state the fact, and an exclamation mark would emphasise it instead of marking the calm check.',
    hints: ['Decide what the walker already knows and what is still uncertain.', 'Use the scene as well as the word order to understand this message.'],
    worked: 'You brought the map? The question mark shows that the walker wants confirmation. You brought the map. would confidently state something instead.',
  },
  {
    key: 'spellbook-10',
    context: 'A visitor calmly asks two separate things about the route. The visitor wants both a path name and a yes-or-no answer about a river crossing.',
    lines: [['path', 'Which path leads home'], ['crossing', 'Does it cross the river']],
    accepted: [{ path: '?', crossing: '?' }],
    demand: 'Maintain two question purposes with different answer types; do not assume adjacent lines must use different marks.',
    explanation: 'Which path leads home? asks for a path, and Does it cross the river? asks for yes or no. Both need question marks here. Full stops or exclamation marks do not express the two calm questions the visitor is asking.',
    hints: ['Think about the two pieces of information the visitor needs.', 'Each line has its own job. Adjacent lines may need the same kind of ending.'],
    worked: 'Which path leads home? Does it cross the river? Both lines are questions even though the replies would be different kinds of information.',
  },
  {
    key: 'spellbook-11',
    context: 'First, a team cheers its result with strong excitement; show that excitement in the ending. Later, the team writes the same words as a calm factual record in its log, without emphasis.',
    lines: [['cheer', 'We won the race'], ['log', 'We won the race']],
    accepted: [{ cheer: '!', log: '.' }],
    demand: 'Contrast two purposes for identical words: emphatic celebration versus neutral record. Context rather than vocabulary changes the chosen ending.',
    explanation: 'We won the race! gives the cheer the strong excitement requested. We won the race. suits the later calm log. A question mark would express uncertainty not present in either use; exchanging the other endings would exchange their requested tones.',
    hints: ['The words stay the same, but the two situations change.', 'Compare why the team speaks first with why it writes later.'],
    worked: 'We won the race! is the excited cheer. We won the race. is the calm log entry. The words are identical, but their purposes call for different endings here.',
  },
];

// Protect the reviewed reference used by the validator from accidental mutation.
function freeze<T>(value: T): T {
  if (value !== null && typeof value === 'object' && !Object.isFrozen(value)) {
    Object.values(value).forEach(freeze);
    Object.freeze(value);
  }
  return value;
}

export const STARTER_PUNCTUATION_TASKS: readonly TaskDefinition[] = freeze(authored.map((item): TaskDefinition => {
  const descriptor = { familyId: 'english.punctuation', equivalenceVersion: 'r1', authoredKey: item.key, parameters: {} };
  return {
    canonicalQuestionId: canonicalQuestionId(descriptor), descriptor, contentRevision: 'starter-punctuation-1',
    skillId: 'E06', objectiveId: 'E06-punctuation', band: 'support', contextualSkillIds: [], curriculum,
    demandRationale: `${item.demand} Earlier terminal-punctuation consolidation, not a core or stretch Years 3–4 punctuation claim.`,
    instructionText: neutralText,
    assessedText: `${item.context}\n${item.lines.map(([, line]) => `${line} ___`).join('\n')}`,
    responseSpec: {
      kind: 'punctuation', slots: item.lines.map(([id, label]) => ({ id, label, options })),
      requiredSlotIds: item.lines.map(([id]) => id),
    },
    answerRule: { kind: 'accepted-responses', responses: item.accepted.map(slots => ({ kind: 'punctuation', slots })) },
    explanation: item.explanation,
    hints: [{ id: `${item.key}-hint-1`, text: item.hints[0] }, { id: `${item.key}-hint-2`, text: item.hints[1] }],
    workedSupport: { id: `${item.key}-worked`, text: item.worked },
    narration: { neutralText, assessedTextMayBeSpokenBeforeCheck: false },
    review: {
      status: 'approved', reviewer: 'Codex WP03-03A author and bounded content reviewer (AI; not a qualified educator)',
      rationale: `All finite endings reviewed against this context, with both hints and narration checked for answer leakage. ${item.demand}`,
      evidenceRef: 'docs/content-review/starter-punctuation.md',
    },
  };
}));

const anchorId = 'lif.english.punctuation.r1.spellbook-anchor';
// Literal nine-pair oracle: no evaluator or answerRule is used to create these cases.
export const STARTER_PUNCTUATION_MANIFEST: TaskFamilyManifest = freeze<TaskFamilyManifest>({
  moduleId: 'starter-punctuation', familyIds: ['english.punctuation'],
  taskIds: STARTER_PUNCTUATION_TASKS.map(task => task.canonicalQuestionId),
  retainedTaskIds: STARTER_PUNCTUATION_TASKS.map(task => task.canonicalQuestionId),
  domainDescription: 'Twelve reviewed support tasks, one or two terminal slots each; exactly ., ? and !; 60 complete maps, 15 accepted and 45 judged wrong. Partial known maps are incomplete; malformed/unknown maps are invalid.',
  reviewEvidenceRef: 'docs/content-review/starter-punctuation.md',
  cases: [
    ...([
      ['.', '.', false], ['.', '?', false], ['.', '!', false],
      ['?', '.', true], ['?', '?', false], ['?', '!', true],
      ['!', '.', false], ['!', '?', false], ['!', '!', false],
    ] as const).map(([question, discovery, correct], index) => ({
      caseId: `anchor-pair-${index + 1}`, canonicalQuestionId: anchorId,
      response: { kind: 'punctuation' as const, slots: { question, discovery } },
      expectedStatus: 'judged' as const, expectedCorrect: correct,
      expectedIssueCodes: [...(question === '?' ? [] : ['punctuation-context']), ...(discovery === '?' ? ['punctuation-context'] : [])],
    })),
    // Independently reviewed non-anchor domains; include every complete map in
    // the downstream manifest, not merely one reachable answer per task.
    ...([
      ['spellbook-01', ['record'], ['.'], ['.']],
      ['spellbook-02', ['lantern'], ['?'], ['?']],
      ['spellbook-03', ['request'], ['?'], ['?']],
      ['spellbook-04', ['thought'], ['.'], ['.']],
      ['spellbook-05', ['admiration'], ['.', '!'], ['.!']],
      ['spellbook-06', ['warning'], ['!'], ['!']],
      ['spellbook-07', ['direction'], ['.'], ['.']],
      ['spellbook-08', ['door', 'key'], ['.?', '!?'], ['.!', '?']],
      ['spellbook-09', ['confirmation'], ['?'], ['?']],
      ['spellbook-10', ['path', 'crossing'], ['??'], ['?', '?']],
      ['spellbook-11', ['cheer', 'log'], ['!.'], ['!', '.']],
    ] as const).flatMap(([key, ids, accepted, perSlot]) => (ids.length === 1 ? ['.', '?', '!']
      : ['..', '.?', '.!', '?.', '??', '?!', '!.', '!?', '!!']).map((marks, index) => ({
        caseId: `${key}-pair-${index + 1}`,
        canonicalQuestionId: STARTER_PUNCTUATION_TASKS.find(task => task.descriptor.authoredKey === key)!.canonicalQuestionId,
        response: { kind: 'punctuation' as const, slots: Object.fromEntries(ids.map((id, i) => [id, marks[i]])) },
        expectedStatus: 'judged' as const, expectedCorrect: (accepted as readonly string[]).includes(marks),
        expectedIssueCodes: ids.flatMap((_, i) => perSlot[i].includes(marks[i]) ? [] : ['punctuation-context']),
      }))),
    { caseId: 'anchor-blank', canonicalQuestionId: anchorId, response: { kind: 'punctuation', slots: {} }, expectedStatus: 'incomplete', expectedIssueCodes: [] },
    { caseId: 'anchor-partial', canonicalQuestionId: anchorId, response: { kind: 'punctuation', slots: { question: '?', discovery: null } }, expectedStatus: 'incomplete', expectedIssueCodes: [] },
    { caseId: 'anchor-unknown-slot', canonicalQuestionId: anchorId, response: { kind: 'punctuation', slots: { other: '.' } }, expectedStatus: 'invalid-response', expectedIssueCodes: [] },
    { caseId: 'anchor-extra-slot', canonicalQuestionId: anchorId, response: { kind: 'punctuation', slots: { question: '?', discovery: '.', other: '!' } }, expectedStatus: 'invalid-response', expectedIssueCodes: [] },
    { caseId: 'anchor-malformed-mark', canonicalQuestionId: anchorId, response: { kind: 'punctuation', slots: { question: ' ?', discovery: '.' } }, expectedStatus: 'invalid-response', expectedIssueCodes: [] },
  ],
});
